<?php
declare(strict_types=1);
require __DIR__ . '/auth.php';
require __DIR__ . '/../db.php';
$config = require __DIR__ . '/../config.php';
$pageTitle = 'Tableau de bord - ARA Tech WiFi';
const DASHBOARD_ROUTER_ONLINE_THRESHOLD = 360;
function ara_format_bytes(?int $bytes): string { if ($bytes === null) return '—'; $units=['o','Ko','Mo','Go']; $value=(float)$bytes; $i=0; while($value>=1024 && $i<count($units)-1){$value/=1024;$i++;} return number_format($value,$i===0?0:1,',',' ').' '.$units[$i]; }
function ara_router_snapshot(): array { try{$pdo=ara_db_supabase();$stmt=$pdo->query('SELECT id,snapshot_date,snapshot_time,active_count,received_at,router_identity,router_uptime,router_version,cpu_load,memory_total,memory_free FROM hotspot_snapshots ORDER BY id DESC LIMIT 1');$snapshot=$stmt->fetch(PDO::FETCH_ASSOC);if(!$snapshot)return ['status'=>'UNKNOWN','age_seconds'=>null,'snapshot'=>null,'error'=>null];$last=null;if(!empty($snapshot['received_at'])){try{$last=new DateTimeImmutable((string)$snapshot['received_at']);}catch(Throwable $e){}}if($last===null&&!empty($snapshot['snapshot_date'])&&!empty($snapshot['snapshot_time'])){$parsed=DateTimeImmutable::createFromFormat('Y-m-d H:i:s',$snapshot['snapshot_date'].' '.$snapshot['snapshot_time'],new DateTimeZone('UTC'));if($parsed!==false)$last=$parsed;}if($last===null)return ['status'=>'UNKNOWN','age_seconds'=>null,'snapshot'=>$snapshot,'error'=>null];$now=new DateTimeImmutable('now',new DateTimeZone('UTC'));$age=max(0,$now->getTimestamp()-$last->getTimestamp());return ['status'=>$age<DASHBOARD_ROUTER_ONLINE_THRESHOLD?'ONLINE':'OFFLINE','age_seconds'=>$age,'snapshot'=>$snapshot,'error'=>null];}catch(Throwable $e){error_log('[Dashboard] '.$e->getMessage());return ['status'=>'UNKNOWN','age_seconds'=>null,'snapshot'=>null,'error'=>'Impossible de lire le dernier état du MikroTik.'];}}
$routerState=ara_router_snapshot();$s=$routerState['snapshot']??null;$status=$routerState['status'];$statusLabel=$status==='ONLINE'?'Synchronisation active':($status==='OFFLINE'?'Synchronisation interrompue':'Statut inconnu');require __DIR__.'/header.php';
?>
<div class="container-fluid px-3 px-md-4 py-4">
<div class="card card-custom" id="network-section"><div class="card-header card-header-custom d-flex justify-content-between align-items-center"><span><i class="bi bi-hdd-network"></i> Statut Réseau — Synchronisation MikroTik</span><?php $statusCode=$status;$statusLabelOverride=$statusLabel;require __DIR__.'/components/status-pill.php';unset($statusLabelOverride,$statusCode);?></div><div class="card-body">
<?php if($status==='ONLINE'&&$s):?><?php $alertType='success';$alertIcon='bi bi-check-circle-fill';$alertTitle='MikroTik synchronisé.';require __DIR__.'/components/alert-card.php';unset($alertType,$alertIcon,$alertTitle,$alertMessage);?><?php elseif($status==='OFFLINE'&&$s):?><?php $alertType='warning';$alertIcon='bi bi-exclamation-triangle-fill';$alertTitle='Le dernier heartbeat du MikroTik est périmé.';$alertMessage='Vérifie le scheduler et le script push-hotspot-status.rsc sur le routeur.';require __DIR__.'/components/alert-card.php';unset($alertType,$alertIcon,$alertTitle,$alertMessage);?><?php else:?><?php $alertType='secondary';$alertIcon='bi bi-question-circle-fill';$alertTitle='Aucun snapshot exploitable.';$alertMessage=$routerState['error']??'Le routeur ne s’est pas encore synchronisé avec le serveur.';require __DIR__.'/components/alert-card.php';unset($alertType,$alertIcon,$alertTitle,$alertMessage);?><?php endif;?>
<div class="row g-3 align-items-stretch"> <?php $defs=[['Identité',(string)($s['router_identity']??'—'),'bi-hdd-network','primary'],['Version RouterOS',(string)($s['router_version']??'—'),'bi-cpu','info'],['Uptime',(string)($s['router_uptime']??'—'),'bi-clock-history','primary'],['Sessions actives',isset($s['active_count'])?(string)(int)$s['active_count']:'—','bi-people','success'],['CPU',($s&&$s['cpu_load']!==null)?(int)$s['cpu_load'].' %':'—','bi-speedometer2','warning'],['Mémoire libre',ara_format_bytes(isset($s['memory_free'])?(int)$s['memory_free']:null),'bi-memory','success'],['Mémoire totale',ara_format_bytes(isset($s['memory_total'])?(int)$s['memory_total']:null),'bi-memory','primary'],['Dernière synchronisation',(string)($s['received_at']??'—'),'bi-arrow-repeat','info']];foreach($defs as [$metricLabel,$metricValue,$metricIcon,$metricTone]):?><div class="col-12 col-md-6 col-xl-3"><div class="h-100"><?php require __DIR__.'/components/metric-card.php';?></div></div><?php endforeach;?></div>
<?php if($routerState['age_seconds']!==null):?><div class="mt-3 text-muted small"><i class="bi bi-clock-history"></i> Âge du dernier snapshot : <?= (int)$routerState['age_seconds'] ?> s. Seuil ONLINE : <?= DASHBOARD_ROUTER_ONLINE_THRESHOLD ?> s.</div><?php endif;?><div class="mt-3"><a href="monitoring.php" class="btn btn-outline-primary btn-sm"><i class="bi bi-activity"></i> Ouvrir le monitoring</a></div>
</div></div>
<div class="card card-custom" id="business-section"><div class="card-header card-header-custom d-flex flex-wrap justify-content-between align-items-center gap-2"><span><i class="bi bi-briefcase"></i> Gestion Business</span><select id="period-select" class="form-select form-select-sm" style="width:auto;min-width:150px"><option value="today">Aujourd'hui</option><option value="yesterday">Hier</option><option value="7days">7 derniers jours</option><option value="thismonth" selected>Ce mois</option><option value="lastmonth">Mois précédent</option></select></div><div class="card-body"><div class="alert alert-info py-2 small"><i class="bi bi-info-circle"></i> Les KPI commerciaux utilisent actuellement les <strong>activations Hotspot dédupliquées</strong>. Le <code>on-login</code> MikroTik alimente un journal technique ; ce n'est pas encore un ledger de paiements.</div><div class="row g-3" id="kpi-cards"><div class="col-md-3 col-6"><div class="h-100"><?php $metricLabel="Montant journalisé";$metricValue='--';$metricIcon='bi-cash-stack';$metricTone='success';$metricId='kpi-revenue';require __DIR__.'/components/metric-card.php';unset($metricLabel,$metricValue,$metricIcon,$metricTone,$metricId);?></div></div><div class="col-md-3 col-6"><div class="h-100"><?php $metricLabel='Activations';$metricValue='--';$metricIcon='bi-ticket-perforated';$metricTone='primary';$metricId='kpi-tickets';require __DIR__.'/components/metric-card.php';unset($metricLabel,$metricValue,$metricIcon,$metricTone,$metricId);?></div></div><div class="col-md-3 col-6"><div class="h-100"><?php $metricLabel='Sessions actives';$metricValue='--';$metricIcon='bi-wifi';$metricTone='info';$metricId='kpi-sessions';require __DIR__.'/components/metric-card.php';unset($metricLabel,$metricValue,$metricIcon,$metricTone,$metricId);?></div></div><div class="col-md-3 col-6"><div class="h-100"><?php $metricLabel='Abonnements';$metricValue='--';$metricIcon='bi-calendar-check';$metricTone='warning';$metricId='kpi-subs';require __DIR__.'/components/metric-card.php';unset($metricLabel,$metricValue,$metricIcon,$metricTone,$metricId);?></div></div></div><canvas id="revenueChart" height="90"></canvas><div id="businessDataQuality" class="text-muted small mt-2"></div></div></div>
</div>
<script>
document.addEventListener('DOMContentLoaded',function(){
 const revenueChart=document.getElementById('revenueChart');let chart=null;
 function formatMoney(n){return new Intl.NumberFormat('fr-FR').format(Number(n)||0)+' FCFA';}
 function fetchBusiness(period){fetch('business-summary.php?period='+encodeURIComponent(period),{headers:{'Accept':'application/json'}}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(data=>{if(!data.success)throw new Error(data.message||'Erreur');document.getElementById('kpi-revenue').textContent=formatMoney(data.revenue);document.getElementById('kpi-tickets').textContent=new Intl.NumberFormat('fr-FR').format(data.activation_count??data.tickets_sold??0);document.getElementById('businessDataQuality').textContent=(data.duplicates_removed||0)+' reconnexion(s) technique(s) ignorée(s). Source : '+(data.source_label||'activations Hotspot');if(chart)chart.destroy();chart=new Chart(revenueChart,{type:'bar',data:{labels:(data.revenue_chart||[]).map(x=>x.sale_date),datasets:[{label:'Montants journalisés (FCFA)',data:(data.revenue_chart||[]).map(x=>x.total)}]},options:{responsive:true,scales:{y:{beginAtZero:true}}}});}).catch(e=>{console.error('Business KPI:',e);document.getElementById('kpi-revenue').textContent='N/A';document.getElementById('kpi-tickets').textContent='N/A';});}
 document.getElementById('period-select').addEventListener('change',function(){fetchBusiness(this.value);});fetchBusiness('thismonth');
});
</script>
<?php require __DIR__.'/footer.php'; ?>
